version: "3.9"

services:
  app:
    build: .
    container_name: notification-hub-app
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      APP_PORT: 8080
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
